/**
 * The files the generator writes, loaded rather than read.
 *
 * `openapi.ts` is a module a server imports to serve its own document, so what matters is that it
 * loads and that the value it exports is the document. Matching its text would pass on a module
 * that throws on import, which is the failure this repository keeps finding.
 */
import { Validator } from '@seriousme/openapi-schema-validator';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { JsonSchemaGenerator, openApiDocument } from '../src/index';
import { posts, users } from './fixtures';

const pkgRoot = path.resolve(import.meta.dirname, '..');
const workDir = path.join('test', 'tmp', 'emit');
const absWork = path.join(pkgRoot, workDir);

const analysis = {
  dialect: 'postgres',
  tables: [users(), posts()],
  enums: [],
  relations: [],
  issues: [],
};

async function generate(dir: string, opts: Record<string, unknown>) {
  const out = path.join(workDir, dir);
  const gen = new JsonSchemaGenerator(analysis as never);
  const files = await gen.generate({ outDir: out, format: { enabled: false }, ...opts } as never);
  return { files, abs: path.join(pkgRoot, out) };
}

beforeAll(async () => {
  await fs.rm(absWork, { recursive: true, force: true });
});

afterAll(async () => {
  await fs.rm(absWork, { recursive: true, force: true });
});

describe('what gets written', () => {
  it('writes nothing extra when the document is not asked for', async () => {
    const { abs } = await generate('off', {});
    expect((await fs.readdir(abs)).sort()).toEqual([
      'index.ts',
      'posts.schema.ts',
      'users.schema.ts',
    ]);
  });

  it('writes openapi.ts on document: true', async () => {
    const { abs } = await generate('ts', { document: true, target: 'openapi-3.1' });
    expect(await fs.readdir(abs)).toContain('openapi.ts');
    expect(await fs.readdir(abs)).not.toContain('openapi.json');
  });

  it('writes openapi.json when asked, and both when asked for both', async () => {
    const { abs: j } = await generate('json', { document: { format: 'json' } });
    expect(await fs.readdir(j)).toContain('openapi.json');
    expect(await fs.readdir(j)).not.toContain('openapi.ts');

    const { abs: b } = await generate('both', { document: { format: 'both' } });
    const names = await fs.readdir(b);
    expect(names).toContain('openapi.ts');
    expect(names).toContain('openapi.json');
  });

  it('writes nothing when the document is switched off explicitly', async () => {
    const { abs } = await generate('disabled', { document: { enabled: false } });
    expect(await fs.readdir(abs)).not.toContain('openapi.ts');
  });
});

describe('the emitted module', () => {
  it('loads, and exports the document', async () => {
    const { abs } = await generate('load', { document: true, target: 'openapi-3.1' });
    const mod = await import(pathToFileURL(path.join(abs, 'openapi.ts')).href);
    expect(mod.openapi.openapi).toBe('3.1.1');
    expect(mod.openapi).toEqual(openApiDocument([users(), posts()], { target: 'openapi-3.1' }));
  });

  it('is re-exported from the barrel', async () => {
    const { abs } = await generate('barrel', { document: true, importExtension: 'none' });
    const mod = await import(pathToFileURL(path.join(abs, 'index.ts')).href);
    expect(mod.openapi).toBeTruthy();
    expect(mod.InsertusersSchema).toBeTruthy();
  });

  it('is complete with no formatter, which is the only thing that has to be true of the text', async () => {
    const { abs } = await generate('unformatted', { document: true, format: { enabled: false } });
    const text = await fs.readFile(path.join(abs, 'openapi.ts'), 'utf8');
    expect(text.startsWith('// Generated by DRZL')).toBe(true);
    expect(text.trimEnd().endsWith('as const;')).toBe(true);
  });
});

describe('the emitted json', () => {
  it('parses, and a real validator accepts it', async () => {
    const { abs } = await generate('validjson', {
      document: { format: 'json' },
      target: 'openapi-3.0',
    });
    const doc = JSON.parse(await fs.readFile(path.join(abs, 'openapi.json'), 'utf8'));
    const res = await new Validator().validate(doc);
    expect(JSON.stringify(res.errors ?? [])).toBe('[]');
    expect(res.valid).toBe(true);
    expect(doc.openapi).toBe('3.0.3');
  });

  it('carries the info and servers the config gave it', async () => {
    const { abs } = await generate('meta', {
      document: {
        format: 'json',
        info: { title: 'Shop', version: '3.2.1' },
        servers: [{ url: 'https://api.example.com' }],
      },
    });
    const doc = JSON.parse(await fs.readFile(path.join(abs, 'openapi.json'), 'utf8'));
    expect(doc.info).toMatchObject({ title: 'Shop', version: '3.2.1' });
    expect(doc.servers).toEqual([{ url: 'https://api.example.com' }]);
  });

  it('adds the sub-resource path when the generator is told to include relations', async () => {
    const { abs } = await generate('rel', { document: { format: 'json' }, includeRelations: true });
    const doc = JSON.parse(await fs.readFile(path.join(abs, 'openapi.json'), 'utf8'));
    expect(Object.keys(doc.paths)).toContain('/users/{id}/posts');
  });
});
