echo "==> installing them into an empty project"
# A real foreign key, because the oRPC generator derives relation endpoints from one and a
# schema without any would exercise none of that path.
cp "$FIXTURES/consumer.schema.ts" "$APP/src/db/schema.ts"

# Every kind in the list below, not just zod. Covering one of five is how the published oRPC
# generator came to emit routers that fail `tsc --strict` while this guard stayed green.
#
# "Every generator kind" is what this used to say, and it is not true of the kinds the CLI takes.
# `typebox` and `json-schema` are both in `GeneratorSchema.kind` (packages/cli/src/config.ts) and
# neither is here. Their emitted output is generated by the parity stage further down instead, and
# compiled there under `module nodenext` alone, so neither of them reaches the bundler and node16
# legs of the moduleResolution sweep this config feeds. That is a real gap in this stage's reach,
# named rather than covered over by the word "every".
cp "$FIXTURES/consumer.drzl.config.ts" "$APP/drzl.config.ts"

cd "$APP"
npm init -y >/dev/null
# ESM, because arktype and @orpc/server ship ESM only. Under `moduleResolution: node16` a
# CommonJS consumer genuinely cannot import them, and tsc says so with TS1479. That is correct
# behaviour rather than a defect in generated code, so the fixture has to be the kind of project
# these packages can actually be used from.
node -e "
  const fs = require('fs');
  const p = JSON.parse(fs.readFileSync('package.json', 'utf8'));
  p.type = 'module';
  fs.writeFileSync('package.json', JSON.stringify(p, null, 2));
"
# npm rather than pnpm on purpose: a consumer is unlikely to share this repo's package manager,
# and npm's flat layout is the harsher test of whether `dependencies` are actually declared.
# valibot, arktype, @orpc/server and hono (with @hono/standard-validator) are peers of the
# generators, so the generated tree cannot typecheck without them present, exactly as in a
# consumer's project.
#
# prettier is here because it is now an *optional* peer of @drzl/validation-core rather than
# something bundled into it, and npm does not install optional peers. Naming it is what a
# consumer who wants formatted output does, and it makes this run cover the peer resolving from
# a real install. The stage further down removes it again to cover the other case.
#
# @modelcontextprotocol/server, ai and @valibot/to-json-schema are the MCP and AI generators' half
# of the same rule: the emitted server imports the first, the emitted tools the second, and both
# reach for the third under valibot.
npm install --no-audit --no-fund --loglevel=error \
  "$TARS"/*.tgz drizzle-orm zod valibot arktype effect @orpc/server @trpc/server hono @hono/standard-validator express @types/express fastify @nestjs/common @modelcontextprotocol/server @valibot/to-json-schema ai @tanstack/react-start typescript tsx prettier >/dev/null

if [ ! -e node_modules/.bin/drzl ]; then
  echo "FAIL: the drzl bin did not resolve after a real install." >&2
  exit 1
fi

echo "==> running the README's headline command"
npx drzl generate >/dev/null
