echo "OK: $count packages packed, installed into an empty project, generated, and the output"
echo "    typechecks under bundler, node16 and nodenext, and is compared column by column and value"
echo "    by value against all four first-party drizzle-orm validator modules on each of three"
echo "    dialects and three modes. Every difference either fails this run or is in one of two"
echo "    ledgers by name: ALLOWED, where the difference is deliberate, or DEFECTS, where DRZL is"
echo "    wrong and it is filed rather than fixed and named on every run with what each side"
echo "    emits. Both ledgers are asserted the same way and in both directions, each entry"
echo "    pinning the exact set of probes it covers, so a stale entry fails as loudly as an"
echo "    unledgered difference. That comparison is the guarantee, and it is not \"at least as"
echo "    strict\": most ledger entries have DRZL accepting something official refuses, the run"
echo "    counts them above, and each says why."
echo "    The four generators are cross-checked against each other on every dialect,"
echo "    checked against a real Postgres, a real SQLite and, where MYSQL_URL is set, a real"
echo "    MySQL, with applyDefaults compared against what the database writes, and described the"
echo "    same way by the analyzer under both drizzle-orm majors, bar the differences that stage"
echo "    names one at a time. The same column by"
echo "    column comparison runs a second time against the first-party validators for 0.45.2,"
echo "    where the columns known to differ are counted and named above, each with what DRZL"
echo "    emits, what official emits and which filing it is. Where an official validator crashes"
echo "    instead of answering, DRZL's own verdict on that value is pinned rather than dropped,"
echo "    and settled against a real Postgres, which is asked about the column being left out of an"
echo "    insert as well as about the value it is given. The JSON Schema output compiles under ajv"
echo "    in strict mode, agrees with Postgres wherever the zod output does, and speaks as a fifth"
echo "    voice on every CHECK. Every tarball holds the files its manifest names and nothing from"
echo "    the working tree, and every package npm is serving carries a provenance attestation."
