// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from 'zod';

export const InsertAuthorsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  handle: z
    .string()
    .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
    .refine((v) => v.length >= 3 && [...v].length >= 3, {
      message: 'handle_len: length(handle) >= 3',
    }),
  email: z.string(),
  age: z.number().int().gte(18).lte(2147483647),
});

export const UpdateAuthorsSchema = z.object({
  handle: z
    .string()
    .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
    .refine((v) => v.length >= 3 && [...v].length >= 3, {
      message: 'handle_len: length(handle) >= 3',
    })
    .optional(),
  email: z.string().optional(),
  age: z.number().int().gte(18).lte(2147483647).optional(),
});

export const SelectAuthorsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  handle: z
    .string()
    .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
    .refine((v) => v.length >= 3 && [...v].length >= 3, {
      message: 'handle_len: length(handle) >= 3',
    }),
  email: z.string(),
  age: z.number().int().gte(18).lte(2147483647),
});

export type InsertAuthorsInput = z.input<typeof InsertAuthorsSchema>;
export type UpdateAuthorsInput = z.input<typeof UpdateAuthorsSchema>;
export type SelectAuthorsOutput = z.output<typeof SelectAuthorsSchema>;

export const NestedInsertAuthorsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  handle: z
    .string()
    .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
    .refine((v) => v.length >= 3 && [...v].length >= 3, {
      message: 'handle_len: length(handle) >= 3',
    }),
  email: z.string(),
  age: z.number().int().gte(18).lte(2147483647),
  posts: z
    .array(
      z.object({
        id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
        title: z
          .string()
          .refine((v) => v.length <= 80 || [...v].length <= 80, {
            message: 'at most 80 characters',
          }),
        status: z.enum(['draft', 'live'] as const),
      })
    )
    .optional(),
});

export type NestedInsertAuthorsInput = z.input<typeof NestedInsertAuthorsSchema>;

export const NestedSelectAuthorsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  handle: z
    .string()
    .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
    .refine((v) => v.length >= 3 && [...v].length >= 3, {
      message: 'handle_len: length(handle) >= 3',
    }),
  email: z.string(),
  age: z.number().int().gte(18).lte(2147483647),
  posts: z
    .array(
      z.object({
        id: z.number().int().gte(-2147483648).lte(2147483647),
        authorId: z.number().int().gte(-2147483648).lte(2147483647),
        title: z
          .string()
          .refine((v) => v.length <= 80 || [...v].length <= 80, {
            message: 'at most 80 characters',
          }),
        status: z.enum(['draft', 'live'] as const),
      })
    )
    .optional(),
});

export type NestedSelectAuthorsOutput = z.output<typeof NestedSelectAuthorsSchema>;
