// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

/**

 * Every CHECK, unique constraint, primary and foreign key on each table, as data.

 *

 * Generated beside the schemas rather than derived from them: a validator states what a value

 * must look like and says nothing about which constraint said so, and the two constraints a

 * per-row schema cannot check at all, uniqueness and a foreign key, are not in it in any form.

 */

/** What a constraint is. */
export type DrzlConstraintKind =
  'primaryKey' | 'unique' | 'foreignKey' | 'check' | 'maxLength' | 'maxBytes';

/** One constraint on one table. */
export interface DrzlConstraint {
  /** Stable within the table. The SQL constraint name where the declaration has one. */
  id: string;
  /** The SQL constraint name, absent where the declaration did not give one. */
  name?: string;
  kind: DrzlConstraintKind;
  /** The columns the constraint is about, in declaration order. */
  columns: string[];
  /** The rule as a sentence, for a form with nothing better to show. */
  rule: string;
  /** Whether a generated schema can reject a row for this constraint. */
  enforced: boolean;
  /** The clauses nothing in these schemas checks, and why. */
  unenforced?: { part: string; reason: string }[];
  /** The exact messages the generated schemas attach for this constraint. */
  messages?: string[];
  /** Bounds folded into a column's range, which is where the constraint name is lost. */
  bounds?: { column: string; operator: string; value: string }[];
  /** A set of literals folded into an enum, which is the other place it is lost. */
  values?: { column: string; values: string[]; kind: 'number' | 'string' };
  /** Where a foreign key points. */
  references?: {
    table: string;
    schema?: string;
    columns: string[];
    onDelete?: string;
    onUpdate?: string;
  };
}

/** Every constraint on one table. */
export interface DrzlTableConstraints {
  /** The SQL table name, which is not the Drizzle export name this is exported under. */
  table: string;
  /** The SQL schema, present only when the table names one. */
  schema?: string;
  constraints: DrzlConstraint[];
}

/** Every constraint on `authors`. */
export const authorsConstraints: DrzlTableConstraints = {
  table: 'authors',
  constraints: [
    {
      id: 'authors_pkey',
      kind: 'primaryKey',
      columns: ['id'],
      rule: 'PRIMARY KEY (id)',
      enforced: false,
    },
    {
      id: 'authors_handle_key',
      name: 'authors_handle_key',
      kind: 'unique',
      columns: ['handle'],
      rule: 'UNIQUE (handle)',
      enforced: false,
    },
    {
      id: 'author_adult',
      name: 'author_adult',
      kind: 'check',
      columns: ['age'],
      rule: 'CHECK (age >= 18)',
      enforced: true,
      bounds: [
        {
          column: 'age',
          operator: '>=',
          value: '18',
        },
      ],
    },
    {
      id: 'handle_len',
      name: 'handle_len',
      kind: 'check',
      columns: ['handle'],
      rule: 'CHECK (length(handle) >= 3)',
      enforced: true,
      messages: ['handle_len: length(handle) >= 3'],
    },
    {
      id: 'authors_handle_maxlength',
      kind: 'maxLength',
      columns: ['handle'],
      rule: 'at most 20 characters',
      enforced: true,
      messages: ['at most 20 characters'],
    },
  ],
};

/** Every constraint on `posts`. */
export const postsConstraints: DrzlTableConstraints = {
  table: 'posts',
  constraints: [
    {
      id: 'posts_pkey',
      kind: 'primaryKey',
      columns: ['id'],
      rule: 'PRIMARY KEY (id)',
      enforced: false,
    },
    {
      id: 'posts_authorId_fkey',
      kind: 'foreignKey',
      columns: ['authorId'],
      rule: 'FOREIGN KEY (authorId) REFERENCES authors (id)',
      enforced: false,
      references: {
        table: 'authors',
        columns: ['id'],
      },
    },
    {
      id: 'status_valid',
      name: 'status_valid',
      kind: 'check',
      columns: ['status'],
      rule: "CHECK (status IN ('draft', 'live'))",
      enforced: true,
      values: {
        column: 'status',
        values: ['draft', 'live'],
        kind: 'string',
      },
    },
    {
      id: 'posts_title_maxlength',
      kind: 'maxLength',
      columns: ['title'],
      rule: 'at most 80 characters',
      enforced: true,
      messages: ['at most 80 characters'],
    },
  ],
};

/** Every table's constraints, keyed by the Drizzle export name its schemas are named after. */
export const constraintsByTable: Record<string, DrzlTableConstraints> = {
  authors: authorsConstraints,
  posts: postsConstraints,
};

/** A validation issue traced back to the constraint that caused it. */
export interface DrzlConstraintMatch {
  constraint: DrzlConstraint;
  /**
   * The column to put the message on.
   *
   * Taken from the issue where the library named one, and from the constraint where it did not.
   * Valibot reports a row-level check with an empty path, so without the fallback a form would
   * have a message and nowhere to show it.
   */
  column?: string;
  /**
   * How the constraint was identified.
   *
   * `message` is an exact match on a string these schemas wrote, and is the only tier that is
   * certain. `bound` matched the numeric bound the library put on the issue against a bound this
   * constraint folded, which is what a folded CHECK leaves to match on once its name is gone.
   * `column` is the last resort: the column has exactly one constraint stated in the validator's
   * own vocabulary, so nothing else on the issue can be wrong about which.
   */
  matchedBy: 'message' | 'bound' | 'column';
}

/**
 * The column an issue is about, across the path shapes these libraries use.
 *
 * zod and ArkType spell a path item as the key itself; valibot spells it as an object carrying
 * one. The last key is taken rather than the first, so an issue inside an array or a nested
 * payload names the field rather than the collection holding it.
 */
function drzlIssueColumn(issue: any): string | undefined {
  const path = issue?.path;
  if (!Array.isArray(path)) return undefined;
  for (let i = path.length - 1; i >= 0; i--) {
    const item: any = path[i];
    if (typeof item === 'string') return item;
    if (item && typeof item === 'object' && typeof item.key === 'string') return item.key;
  }
  return undefined;
}

/**
 * The numeric bound an issue reports, as a decimal string, or nothing.
 *
 * Measured rather than guessed: zod 4.4.3 puts `minimum`/`maximum` on a `too_small`/`too_big`
 * issue and valibot 1.4.2 puts `requirement` on a `min_value`/`max_value` one. A bigint bound
 * is read too, since a 64 bit column's range is not representable as a number.
 */
function drzlIssueBound(issue: any): string | undefined {
  for (const key of ['minimum', 'maximum', 'requirement']) {
    const v = issue?.[key];
    if (typeof v === 'number' || typeof v === 'bigint') return String(v);
  }
  return undefined;
}

/**
 * The constraint a validation issue came from, or nothing.
 *
 * Three tiers, because a constraint does not always survive into the issue in the same form. Every
 * constraint stated as a predicate carries a message these schemas wrote, and that is an exact
 * lookup. A numeric CHECK is deliberately folded into the column's own range instead, so the
 * failure is worded by the library and the constraint name is nowhere in it; the bound is, and it
 * is matched on that. A set constraint becomes an enum and leaves neither, so it is resolved by
 * the column alone, which is safe only because a column can carry one such constraint at most.
 *
 * The two folds are kept apart rather than pooled, and that is what stops the third tier
 * over-claiming. A folded bound always reports its bound, in every library measured, so an issue
 * on that column carrying **no** bound is not that constraint: it is the field failing to be a
 * number at all. Pooling them answered `invalid_type` on a column with a numeric CHECK with the
 * CHECK, which is a rule the row did not break.
 *
 * Returns nothing rather than a guess, for the same reason. A `too_small` reporting the column's
 * own type bound has no matching constraint and gets no answer.
 */
export function constraintForIssue(table: string, issue: unknown): DrzlConstraintMatch | undefined {
  const ledger = constraintsByTable[table];
  if (!ledger) return undefined;
  const raw: any = issue;
  const column = drzlIssueColumn(raw);
  const message = typeof raw?.message === 'string' ? raw.message : undefined;

  if (message !== undefined) {
    for (const constraint of ledger.constraints) {
      if (!constraint.messages || constraint.messages.indexOf(message) < 0) continue;
      if (column !== undefined && constraint.columns.indexOf(column) < 0) continue;
      return {
        constraint,
        column: column ?? constraint.columns[0],
        matchedBy: 'message',
      };
    }
  }

  if (column === undefined) return undefined;

  const bound = drzlIssueBound(raw);
  if (bound !== undefined) {
    const hit = ledger.constraints.find(
      (c) => c.bounds && c.bounds.some((b) => b.column === column && b.value === bound)
    );
    return hit ? { constraint: hit, column, matchedBy: 'bound' } : undefined;
  }

  const sets = ledger.constraints.filter((c) => c.values && c.values.column === column);
  return sets.length === 1 ? { constraint: sets[0], column, matchedBy: 'column' } : undefined;
}
