// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from 'zod';

export const InsertPostsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  authorId: z.number().int().gte(-2147483648).lte(2147483647),
  title: z
    .string()
    .refine((v) => v.length <= 80 || [...v].length <= 80, { message: 'at most 80 characters' }),
  status: z.enum(['draft', 'live'] as const),
});

export const UpdatePostsSchema = z.object({
  authorId: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  title: z
    .string()
    .refine((v) => v.length <= 80 || [...v].length <= 80, { message: 'at most 80 characters' })
    .optional(),
  status: z.enum(['draft', 'live'] as const).optional(),
});

export const SelectPostsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  authorId: z.number().int().gte(-2147483648).lte(2147483647),
  title: z
    .string()
    .refine((v) => v.length <= 80 || [...v].length <= 80, { message: 'at most 80 characters' }),
  status: z.enum(['draft', 'live'] as const),
});

export type InsertPostsInput = z.input<typeof InsertPostsSchema>;
export type UpdatePostsInput = z.input<typeof UpdatePostsSchema>;
export type SelectPostsOutput = z.output<typeof SelectPostsSchema>;

export const NestedSelectPostsSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  authorId: z.number().int().gte(-2147483648).lte(2147483647),
  title: z
    .string()
    .refine((v) => v.length <= 80 || [...v].length <= 80, { message: 'at most 80 characters' }),
  status: z.enum(['draft', 'live'] as const),
  authors: z
    .object({
      id: z.number().int().gte(-2147483648).lte(2147483647),
      handle: z
        .string()
        .refine((v) => v.length <= 20 || [...v].length <= 20, { message: 'at most 20 characters' })
        .refine((v) => v.length >= 3 && [...v].length >= 3, {
          message: 'handle_len: length(handle) >= 3',
        }),
      email: z.string(),
      age: z.number().int().gte(18).lte(2147483647),
    })
    .nullable()
    .optional(),
});

export type NestedSelectPostsOutput = z.output<typeof NestedSelectPostsSchema>;
