#!/usr/bin/env bash
#
# DRZL's generated schemas against drizzle-orm's own, on the same table, for the same inputs.
#
# Not part of CI. Benchmarks on a shared runner measure the runner, and a number that moves with
# the weather gets ignored or, worse, chased. This is run by hand when a change might plausibly
# have cost something, and the figures go in the docs with the machine named.
#
# What it measures:
#   1. how much each generated file weighs, which is what ships in the consumer's bundle
#   2. parse throughput on rows that pass
#   3. parse throughput on rows that fail, which is the path an API actually spends time in
#   4. how many of the constraints the database enforces each schema actually reproduces
#
# The fourth is the one that matters. Throughput is only comparable between two schemas that
# enforce the same thing, and these two do not: that is the point of the project.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "==> packing"
cd "$ROOT"
pnpm -r --filter='{packages/*}' exec pnpm pack --pack-destination "$WORK/tars" >/dev/null 2>&1

echo "==> installing into an empty project"
mkdir -p "$WORK/app/src"
cd "$WORK/app"
npm init -y >/dev/null 2>&1
npm pkg set type=module >/dev/null
npm install --no-audit --no-fund --loglevel=error \
  "$WORK"/tars/*.tgz drizzle-orm@1.0.0-rc.4 zod tsx >/dev/null

cat > src/schema.ts <<'SCHEMA'
import { pgTable, text, integer, varchar, boolean, timestamp, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// A table shaped like a real one: a few constrained columns among ordinary ones, which is where
// the two schemas differ and therefore the only honest place to compare them.
export const users = pgTable(
  'users',
  {
    id: integer().notNull(),
    email: varchar({ length: 255 }).notNull(),
    name: text().notNull(),
    age: integer().notNull(),
    tier: text().notNull(),
    score: integer().notNull(),
    active: boolean().notNull(),
    createdAt: timestamp({ mode: 'string' }).notNull(),
  },
  (t) => [
    check('age_c', sql`${t.age} >= 18`),
    check('score_c', sql`${t.score} BETWEEN 0 AND 100`),
    check('tier_c', sql`${t.tier} IN ('free', 'pro', 'team')`),
    check('name_c', sql`length(${t.name}) >= 2`),
  ]
);
SCHEMA

cat > drzl.config.ts <<'CONFIG'
import { defineConfig } from '@drzl/cli/config';
export default defineConfig({
  schema: 'src/schema.ts',
  outDir: 'src/gen',
  generators: [{ kind: 'zod', path: 'src/gen/zod' }],
});
CONFIG

npx drzl generate --config drzl.config.ts >/dev/null

cat > bench.ts <<'BENCH'
import { statSync } from 'node:fs';
import { SelectusersSchema as drzl } from './src/gen/zod/users.zod';
import { createSelectSchema } from 'drizzle-orm/zod';
import { users } from './src/schema';

const official: any = createSelectSchema(users);

const VALID = {
  id: 1,
  email: 'a@b.co',
  name: 'Ada',
  age: 30,
  tier: 'pro',
  score: 50,
  active: true,
  createdAt: '2026-08-02T00:00:00Z',
};

/**
 * Rows the database refuses. Each violates exactly one CHECK and is otherwise well typed, so a
 * schema without CHECK support accepts every one of them.
 */
const REJECTED = [
  { ...VALID, age: 17 },
  { ...VALID, score: 101 },
  { ...VALID, tier: 'enterprise' },
  { ...VALID, name: 'A' },
];

/** Rows that are wrong in a way both schemas can see, so the failure path is comparable. */
const MISTYPED = [
  { ...VALID, id: 'x' },
  { ...VALID, active: 'yes' },
];

function opsPerSecond(fn: () => void): number {
  // Warm up first: the first thousand parses are measuring the JIT, not the schema.
  for (let i = 0; i < 2000; i++) fn();
  const start = process.hrtime.bigint();
  let n = 0;
  while (process.hrtime.bigint() - start < 1_000_000_000n) {
    for (let i = 0; i < 200; i++) fn();
    n += 200;
  }
  const elapsed = Number(process.hrtime.bigint() - start) / 1e9;
  return Math.round(n / elapsed);
}

const caught = (schema: any, rows: unknown[]) =>
  rows.filter((r) => !schema.safeParse(r).success).length;

const bytes = statSync('src/gen/zod/users.zod.ts').size;

const rows = [
  ['constraints the database enforces, reproduced', `${caught(drzl, REJECTED)}/4`, `${caught(official, REJECTED)}/4`],
  ['generated bytes for this table', String(bytes), 'n/a, not a file'],
  ['parses/sec, row accepted', String(opsPerSecond(() => drzl.safeParse(VALID))), String(opsPerSecond(() => official.safeParse(VALID)))],
  [
    'parses/sec, row mistyped',
    String(opsPerSecond(() => drzl.safeParse(MISTYPED[0]))),
    String(opsPerSecond(() => official.safeParse(MISTYPED[0]))),
  ],
  [
    'parses/sec, row violates a CHECK',
    String(opsPerSecond(() => drzl.safeParse(REJECTED[0]))),
    String(opsPerSecond(() => official.safeParse(REJECTED[0]))),
  ],
];

const w = [Math.max(...rows.map((r) => r[0].length)), 12, 12];
const line = (a: string, b: string, c: string) =>
  `${a.padEnd(w[0])}  ${b.padStart(w[1])}  ${c.padStart(w[2])}`;
console.log('');
console.log(line('', 'DRZL', 'drizzle-orm'));
console.log('-'.repeat(w[0] + w[1] + w[2] + 4));
for (const r of rows) console.log(line(r[0], r[1], r[2]));
console.log('');
console.log(`node ${process.version}`);
BENCH

echo "==> benchmarking"
npx tsx bench.ts
