#!/usr/bin/env bash
#
# Where the time in one `drzl generate` goes, on a schema large enough for the answer to mean
# something.
#
# Every fixture in this repository is tens of columns. That is the right size for a correctness
# test and the wrong size for a timing claim: at that size the whole run is process startup, and
# any conclusion drawn from it is a conclusion about node. This runs the real CLI on schemas of
# 25 to 400 tables, generated by scripts/gen-wide-schema.mjs, and splits the run into the phases
# a change could plausibly move.
#
# Not part of CI, for the reason bench.sh gives: a benchmark on a shared runner measures the
# runner. Run by hand, name the machine, and quote the spread rather than one figure.
#
# The two caches that decide the headline number:
#   jiti writes its transpiled schema to os.tmpdir()/jiti when the module that called it lives
#   inside node_modules, which is where @drzl/analyzer lives, and to node_modules/.cache/jiti
#   otherwise. Both are cleared before a cold measurement. A run that clears only the second one
#   measures a warm cache and calls it cold.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

REPS="${BENCH_REPS:-7}"
SIZES="${BENCH_SIZES:-25 50 100 200 400}"
HEADLINE="${BENCH_HEADLINE:-200}"

echo "==> packing"
cd "$ROOT"
pnpm -r --filter='{packages/*}' exec pnpm pack --pack-destination "$WORK/tars" >/dev/null 2>&1

echo "==> installing into an empty project"
mkdir -p "$WORK/app/schemas"
cd "$WORK/app"
npm init -y >/dev/null 2>&1
npm pkg set type=module >/dev/null
npm install --no-audit --no-fund --loglevel=error \
  "$WORK"/tars/*.tgz drizzle-orm@1.0.0-rc.4 zod valibot arktype @sinclair/typebox >/dev/null

echo "==> generating fixtures"
for n in $SIZES; do
  node "$ROOT/scripts/gen-wide-schema.mjs" --tables "$n" --columns 12 --checks 4 --enums 8 \
    > "schemas/t$n.ts"
done
# The same table count with more columns, and the same table count with no CHECK constraints, so
# the scaling table can say which of the three the cost actually follows.
node "$ROOT/scripts/gen-wide-schema.mjs" --tables "$HEADLINE" --columns 30 --checks 4 --enums 8 \
  > "schemas/t${HEADLINE}-wide.ts"
node "$ROOT/scripts/gen-wide-schema.mjs" --tables "$HEADLINE" --columns 12 --checks 0 --enums 8 \
  > "schemas/t${HEADLINE}-nochecks.ts"

for kinds in 0 1 4; do
  case "$kinds" in
    0) list='' ;;
    1) list="{ kind: 'zod', path: 'out$kinds/zod' }" ;;
    4) list="{ kind: 'zod', path: 'out$kinds/zod' }, { kind: 'valibot', path: 'out$kinds/valibot' }, { kind: 'arktype', path: 'out$kinds/arktype' }, { kind: 'typebox', path: 'out$kinds/typebox' }" ;;
  esac
  cat > "gen$kinds.config.ts" <<CONFIG
import { defineConfig } from '@drzl/cli/config';
export default defineConfig({
  schema: 'schemas/t$HEADLINE.ts',
  outDir: 'out$kinds',
  generators: [$list],
});
CONFIG
done

CLI=node_modules/@drzl/cli/dist/cli.js
JITI_TMP="${TMPDIR:-/tmp}/jiti"

# Both caches gone, so a cold measurement is cold.
cold() { rm -rf "$JITI_TMP" node_modules/.cache/jiti; }

# Median and range of REPS wall-clock timings of one command, in milliseconds.
timed() {
  local pre="$1"
  shift
  local t=()
  for _ in $(seq 1 "$REPS"); do
    [ "$pre" = cold ] && cold
    local s e
    s=$(date +%s%N)
    "$@" >/dev/null 2>&1
    e=$(date +%s%N)
    t+=($(((e - s) / 1000000)))
  done
  printf '%s\n' "${t[@]}" | sort -n | awk '{a[NR]=$1} END {printf "%d [%d..%d]", a[int((NR+1)/2)], a[1], a[NR]}'
}

cat > phases.mjs <<'PHASES'
/**
 * The same phases from inside one process, which is the only way to see them apart.
 *
 * The first analyze in a process pays for the transpile of the schema module; every later one in
 * the same process does not, which is also what `drzl watch` sees after its first pass.
 */
import path from 'node:path';
import { performance } from 'node:perf_hooks';

const SCHEMA = process.argv[2];
const REPS = Number(process.env.REPS ?? 5);
const { SchemaAnalyzer } = await import('@drzl/analyzer');
const gens = {
  zod: (await import('@drzl/generator-zod')).ZodGenerator,
  valibot: (await import('@drzl/generator-valibot')).ValibotGenerator,
  arktype: (await import('@drzl/generator-arktype')).ArkTypeGenerator,
  typebox: (await import('@drzl/generator-typebox')).TypeBoxGenerator,
};
const stat = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  return [s[0], s[(s.length - 1) >> 1], s[s.length - 1]];
};

let t = performance.now();
const analysis = await new SchemaAnalyzer(SCHEMA).analyze({
  includeRelations: true,
  validateConstraints: true,
});
const first = performance.now() - t;

const again = [];
for (let i = 0; i < REPS; i++) {
  t = performance.now();
  await new SchemaAnalyzer(SCHEMA).analyze({ includeRelations: true, validateConstraints: true });
  again.push(performance.now() - t);
}

const emit = {};
let files = 0;
let bytes = 0;
for (const [kind, G] of Object.entries(gens)) {
  const runs = [];
  for (let i = 0; i < REPS; i++) {
    const captured = [];
    const gen = new G(analysis);
    t = performance.now();
    await gen.generate({
      outDir: path.join('/never/written', kind),
      outputDir: path.join('/never/written', kind),
      fileSink: { mkdir: () => {}, writeFile: (_p, c) => captured.push(c) },
    });
    runs.push(performance.now() - t);
    if (kind === 'zod') {
      files = captured.length;
      bytes = captured.reduce((n, c) => n + Buffer.byteLength(c), 0);
    }
  }
  emit[kind] = stat(runs);
}

console.log(
  JSON.stringify({
    tables: analysis.tables.length,
    columns: analysis.tables.reduce((n, tb) => n + tb.columns.length, 0),
    checks: analysis.tables.reduce((n, tb) => n + (tb.checks?.length ?? 0), 0),
    first,
    again: stat(again),
    emit,
    files,
    bytes,
  })
);
PHASES

cat > attribute.mjs <<'ATTR'
/**
 * Which package spent the CPU in one real `drzl generate`, from a V8 sampling profile.
 *
 * Self time, bucketed by the package the sampled frame came from. This is the number that decides
 * whether per-table generation is worth parallelising: it says how much of the run is per-table
 * work at all.
 */
import { readFileSync, readdirSync } from 'node:fs';
const dir = process.argv[2];
const p = JSON.parse(readFileSync(`${dir}/${readdirSync(dir)[0]}`, 'utf8'));
const byId = new Map(p.nodes.map((n) => [n.id, n]));
const self = new Map();
for (let i = 0; i < p.samples.length; i++) {
  const cf = byId.get(p.samples[i]).callFrame;
  const url = cf.url || '';
  const dt = (p.timeDeltas[i] ?? 0) / 1000;
  let bucket;
  if (url.startsWith('node:')) bucket = 'node internals (module load, fs)';
  else if (url.includes('/@drzl/generator-')) bucket = '@drzl/generator-* (per table)';
  else if (url.includes('/@drzl/validation-core/')) bucket = '@drzl/validation-core (per column)';
  else if (url.includes('/@drzl/analyzer/')) bucket = '@drzl/analyzer (per table)';
  else if (url.includes('/@drzl/cli/')) bucket = '@drzl/cli';
  else if (url.includes('/jiti/')) bucket = 'jiti';
  else if (url.includes('/drizzle-orm/')) bucket = 'drizzle-orm (evaluating the schema)';
  else if (url.includes('node_modules/'))
    bucket = 'node_modules/' + url.replace(/^.*node_modules\//, '').split('/')[0];
  // A sampled frame with no url is a v8 or libuv internal, named by its function. Some of those
  // names are whole regular expressions, which would set the width of the printed table.
  else if (url === '') {
    const fn = cf.functionName || 'program';
    bucket = `v8 ${fn.startsWith('RegExp:') ? 'RegExp' : fn}`;
  } else bucket = 'the schema module itself';
  self.set(bucket, (self.get(bucket) ?? 0) + dt);
}
const total = [...self.values()].reduce((a, b) => a + b, 0);
const rows = [...self.entries()].sort((a, b) => b[1] - a[1]).filter(([, v]) => v >= 1);
const w = Math.max(...rows.map((r) => r[0].length));
console.log(`  ${'where'.padEnd(w)}  ${'ms'.padStart(8)}  ${'share'.padStart(6)}`);
console.log('  ' + '-'.repeat(w + 18));
for (const [k, v] of rows) {
  console.log(`  ${k.padEnd(w)}  ${v.toFixed(1).padStart(8)}  ${((v / total) * 100).toFixed(1).padStart(5)}%`);
}
console.log(`  ${'total sampled'.padEnd(w)}  ${total.toFixed(1).padStart(8)}`);
ATTR

echo ""
echo "One drzl generate on schemas/t$HEADLINE.ts, end to end, wall clock"
echo ""
printf '  %-40s  %s\n' "command" "ms, median [min..max]"
printf '  %s\n' "------------------------------------------------------------------"
printf '  %-40s  %s\n' "node -e '' (the floor)" "$(timed warm node -e '')"
printf '  %-40s  %s\n' "drzl --version (CLI bundle load)" "$(timed warm node $CLI --version)"
printf '  %-40s  %s\n' "drzl analyze, cold jiti cache" "$(timed cold node $CLI analyze schemas/t$HEADLINE.ts)"
printf '  %-40s  %s\n' "drzl analyze, warm jiti cache" "$(timed warm node $CLI analyze schemas/t$HEADLINE.ts)"
node $CLI generate --config gen1.config.ts >/dev/null 2>&1 || true
node $CLI generate --config gen4.config.ts >/dev/null 2>&1 || true
printf '  %-40s  %s\n' "drzl generate, 0 generators" "$(timed warm node $CLI generate --config gen0.config.ts)"
printf '  %-40s  %s\n' "drzl generate, 1 generator, cold" "$(timed cold node $CLI generate --config gen1.config.ts)"
printf '  %-40s  %s\n' "drzl generate, 1 generator, warm" "$(timed warm node $CLI generate --config gen1.config.ts)"
printf '  %-40s  %s\n' "drzl generate, 4 generators, warm" "$(timed warm node $CLI generate --config gen4.config.ts)"
printf '  %-40s  %s\n' "drzl generate, 1 gen, --dry-run" "$(timed warm node $CLI generate --config gen1.config.ts --dry-run)"

echo ""
echo "Inside the process, by schema size, ms"
echo ""
printf '  %-22s  %7s %7s %6s  %22s  %20s  %s\n' \
  "schema" "tables" "columns" "CHECKs" "analyze, first in proc" "analyze, later" "emit, zod / valibot / arktype / typebox"
printf '  %s\n' "--------------------------------------------------------------------------------------------------------------------------------------------"
for f in $(for n in $SIZES; do echo "t$n"; done) "t$HEADLINE-wide" "t$HEADLINE-nochecks"; do
  cold
  REPS=5 node phases.mjs "schemas/$f.ts" | node -e '
    let s = "";
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      const j = JSON.parse(s);
      const one = (a) => `${a[1].toFixed(0)} [${a[0].toFixed(0)}..${a[2].toFixed(0)}]`;
      const e = ["zod", "valibot", "arktype", "typebox"].map((k) => j.emit[k][1].toFixed(0)).join(" / ");
      process.stdout.write(
        `  ${process.argv[1].padEnd(22)}  ${String(j.tables).padStart(7)} ${String(j.columns).padStart(7)} ${String(j.checks).padStart(6)}  ${j.first.toFixed(0).padStart(22)}  ${one(j.again).padStart(20)}  ${e}\n`
      );
    });
  ' "$f"
done

echo ""
echo "Where the CPU went in one drzl generate with 1 generator, cold jiti cache"
echo ""
rm -rf prof-cold
cold
node --cpu-prof --cpu-prof-dir=prof-cold $CLI generate --config gen1.config.ts >/dev/null 2>&1
node attribute.mjs prof-cold

echo ""
echo "The same run with the jiti cache warm, which is every run after the first"
echo ""
rm -rf prof-warm
# Warmed deliberately: the profile above cleared the cache, and a profile taken straight after it
# would be a second cold run under a heading that says warm.
node $CLI generate --config gen1.config.ts >/dev/null 2>&1
node --cpu-prof --cpu-prof-dir=prof-warm $CLI generate --config gen1.config.ts >/dev/null 2>&1
node attribute.mjs prof-warm

echo ""
echo "$REPS repetitions, node $(node --version)"
