// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { Type } from '@sinclair/typebox';
import type { Static } from '@sinclair/typebox';

export const InserttSchema = Type.Object({
  tags: Type.Array(Type.Unknown()),
});

export const UpdatetSchema = Type.Object({
  tags: Type.Optional(Type.Array(Type.Unknown())),
});

export const SelecttSchema = Type.Object({
  tags: Type.Array(Type.Unknown()),
});

export type InserttInput = Static<typeof InserttSchema>;
export type UpdatetInput = Static<typeof UpdatetSchema>;
export type SelecttOutput = Static<typeof SelecttSchema>;
