/**
 * A `GENERATED ALWAYS` column in the generated service types.
 *
 * The emitted `update(id, data)` hands its patch straight to `db.update().set()`, so a key in
 * `Update<T>` is a column name that reaches a real UPDATE. Every server refuses one that names a
 * generated column, with any value at all including NULL. Asked of a real Postgres through PGlite:
 *
 *   update children set span = 7       refused, 428C9 column "span" can only be updated to DEFAULT
 *   update children set span = null    refused, 428C9
 *   update children set span = default accepted, and it is the only accepted form
 *
 * `SET col = DEFAULT` is not something a patch object can express and not something Drizzle's
 * `.set()` produces, so the column has no business in the type.
 *
 * This file builds its own field list rather than calling `updateColumns`, which is why the fix in
 * `@drzl/validation-core` did not reach it. `insertFields` beside it already asked the question.
 *
 * The control is `GENERATED BY DEFAULT AS IDENTITY`, which the same servers accept an UPDATE of.
 * The analyzer reports it as `isGenerated: false`, so it stays, and a fix that dropped it would be
 * over-reaching rather than correct.
 */
import { describe, it, expect } from 'vitest';
import { ServiceGenerator } from '../src';
import type { Analysis } from '@drzl/analyzer';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const analysis: Analysis = {
  dialect: 'postgres',
  tables: [
    {
      name: 'children',
      tsName: 'children',
      columns: [
        // GENERATED BY DEFAULT AS IDENTITY. The analyzer reports isGenerated false, and Postgres
        // accepts an UPDATE of it. It is excluded from the patch for being the key, not for this.
        {
          name: 'id',
          tsType: 'number',
          dbType: 'INTEGER',
          nullable: false,
          hasDefault: true,
          isGenerated: false,
        },
        {
          name: 'b',
          tsType: 'number',
          dbType: 'INTEGER',
          nullable: false,
          hasDefault: false,
          isGenerated: false,
        },
        // GENERATED ALWAYS AS (b * 2) STORED.
        {
          name: 'span',
          tsType: 'number',
          dbType: 'INTEGER',
          nullable: true,
          hasDefault: false,
          isGenerated: true,
        },
        // The control for the other half: a defaulted column need not be written and may be.
        {
          name: 'seenAt',
          tsType: 'Date',
          dbType: 'TIMESTAMP',
          nullable: false,
          hasDefault: true,
          isGenerated: false,
        },
      ],
      primaryKey: { columns: ['id'] },
      unique: [],
      indexes: [],
    },
  ] as never,
  enums: [],
  relations: [],
  issues: [],
} as Analysis;

async function emitted(): Promise<string> {
  const outDir = await fs.mkdtemp(path.join(os.tmpdir(), 'drzl-svc-gen-'));
  await new ServiceGenerator(analysis).generate({ outDir } as never);
  return fs.readFile(path.join(outDir, 'types', 'children.ts'), 'utf8');
}

function block(src: string, name: string): string {
  const start = src.indexOf(`export interface ${name} {`);
  expect(start, `${name} is missing from the emitted types`).toBeGreaterThan(-1);
  return src.slice(start, src.indexOf('}', start));
}

describe('a generated column in the emitted service types', () => {
  it('is absent from the patch type, because no server accepts it in an UPDATE', async () => {
    expect(block(await emitted(), 'Updatechildren')).not.toContain('span');
  });

  it('is absent from the insert type as well, which already asked', async () => {
    expect(block(await emitted(), 'Insertchildren')).not.toContain('span');
  });

  it('is present in the row type, since the database does return it', async () => {
    expect(block(await emitted(), 'Selectchildren')).toContain('span');
  });

  it('leaves a defaulted column in the patch, which an UPDATE may name', async () => {
    expect(block(await emitted(), 'Updatechildren')).toContain('seenAt');
  });
});
