name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Version & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm -w i --frozen-lockfile

      - name: Changesets (PR + publish on merge)
        uses: changesets/action@v1
        with:
          version: pnpm -w changeset:version
          commit: "chore(release): publish"
          title: "Version Packages"
          createGithubReleases: true
          publish: pnpm -r --filter="{packages/*}" run build && pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
